swagger: '2.0'
info:
  version: '1.0'
  title: 'Personal Expense Tracker API with Chatbot Analyst'
paths:
  # Client Routes
  ## About Page
  /about:
    get:
      tags:
        - Client
      description: Returns an about page.
      responses:
        200:
          description: Returns the page.
          schema:
            type: string
        400:
          description: Invalid
  ## User Registration Page
  /register:
    get:
      tags:
        - Client
      description: User registration page.
      responses:
        200:
          description: Returns a user registration page.
        400:
          description: Invalid
  ## User Login Page
  /login:
    get:
      tags:
        - Client
      description: User login page.
      responses:
        200:
          description: Returns a user registration page.
        400:
          description: Invalid
  ## User Expenses Dashboard
  /expenses:
    get:
      tags:
        - Client
      description: User Expenses Dashboard.
      responses:
        200:
          description: Returns an expenses dashboard for the logged in user.

  # ------------------------------------------------------------------------

  # API Routes
  ## User Registration API
  /api/register:
    post:
      tags:
        - Server
      description: Registers user
      responses:
        200:
          description: User registered successfully.
        400:
          description: Invalid characters in "user" were provided.

  /api/login:
    post:
      tags:
        - Server
      description: Logs in user
      responses:
        200:
          description: Successful log in.
        400:
          description: Invalid credentials.

  /api/me:
    post:
      tags:
        - Server
      description: Get current user.
      responses:
        200:
          description: Succesful get.
        400:
          description: Get failed.

  /api/logout:
    post:
      tags:
        - Server
      description: Log out user.
      responses:
        200:
          description: Log out succesful.
        400:
          description: Log out failed.
